name: Build Site

on: 
  # push: 
  #   branches: [master]

  workflow_dispatch:

  repository_dispatch:

jobs:
  build-site:

    runs-on: windows-latest

    steps:      
    - uses: actions/checkout@master

    - name: Run PowerShell script to build site
      id: build
      run: pwsh -command ".\$GITHUB_WORKSPACE\site\Build.ps1"
