name: deploy

on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:  
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'develop'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          source-url: https://nuget.pkg.github.com/pimbrouwers/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build Falco --configuration Release
      - name: Create the package
        run: dotnet pack Falco --configuration Release --include-symbols
      - name: Publish the package to GPR
        run: dotnet nuget push Falco/bin/Release/*.nupkg